services:
  db_mongo:
    build: ./mongo
    container_name: db_mongo
    restart: on-failure
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: >
        mongosh --quiet --username $MONGO_ROOT_USER --password $MONGO_ROOT_PASSWORD --eval 
        'db.getSiblingDB("blog_db").posts.countDocuments() === 5' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  db_mysql:
    image: mysql:9.6
    container_name: db_mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: >
        mysql -u root -p$${MYSQL_ROOT_PASSWORD} -e "SELECT COUNT(*) FROM blog_db.utilisateurs" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
       - mysql_data:/var/lib/mysql
       - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    container_name: fastapi_api
    restart: on-failure
    depends_on:
      db_mongo:
        condition: service_healthy
      db_mysql:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    healthcheck:
      test: >
        curl -f http://localhost:8000/posts && curl -f http://localhost:8000/users || exit 1
      interval: 30s

  admin_mongo:
    image: mongo-express
    restart: on-failure
    depends_on:
      db_mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@db_mongo:27017/

  admin_mysql:
    image: adminer
    restart: on-failure
    depends_on:
      db_mysql:
        condition: service_healthy 
    ports:
      - "8080:8080" 

volumes:
  mongo_data:
    name: mongo_data
  mysql_data:
    name: mysql_data